## ✨ 참고용

# MariaDB 설정
mariadb_host = "localhost"
mariadb_user = "root"
mariadb_password = "password"
mariadb_db = "ffmpeg-video-database"
mariadb_port = "3310"

# 환경 설정
environment = "dev"

host = "localhost:3031"
scheme = "http"
version = "1.0"
basePath = "/api"
title = "ffmpeg-video-modules API"